//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transiction_history
    {
        public int id { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> sender { get; set; }
        public Nullable<int> receiver { get; set; }
        public Nullable<int> drawer { get; set; }
        public Nullable<System.DateTime> withdraw_Time { get; set; }
        public Nullable<System.DateTime> transfer_Time { get; set; }
    
        public virtual client_info client_info { get; set; }
        public virtual client_info client_info1 { get; set; }
        public virtual client_info client_info2 { get; set; }
    }
}
